In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

In [2]:
%load_ext autoreload
%autoreload 2

In [58]:
import os
import sys

sys.path.append(os.path.abspath("common"))
from evaluate import evaluate_predictions
from preprocess import getdfs, get_char_columns, one_hot_encode
from evaluate import get_classification_report, evaluate_predictions
from models import predict_logistic_regression
from models import predict_svc

In [8]:
emoticon_train_df, emoticon_test_df = getdfs(data='emoticon')
text_seq_train_df, text_seq_test_df = getdfs(data='text_seq')
feature_train_df, feature_test_df = getdfs(data='feature')


In [15]:
print(np.array_equal(y_train, text_seq_train_df["label"]))
print(np.array_equal(y_train, feature_train_df["label"]))
print(np.array_equal(y_test, text_seq_test_df["label"]))
print(np.array_equal(y_test, text_seq_test_df["label"]))

NameError: name 'y_train' is not defined

### Emoticon

In [11]:

strings = emoticon_train_df['input_emoticon'].values
common_chars = find_common_characters(strings)

print("Common characters:", common_chars)

strings_after_removal = remove_common_characters(strings, common_chars)
print("Strings after removal of common characters:", strings_after_removal)

Common characters: {'😑', '🚼', '🛐', '🙯', '😣', '🙼', '😛'}
Strings after removal of common characters: ['😻🙠😒', '😪🚅😹', '🚡🙲🛑', '🙐🙪🛆', '🚟🙋😹', '🚧🚜🙕', '🚥😬🚄', '🚡🚔🛓', '\U0001f6dc😚🚠', '🙷😍😿', '🙚😍😸', '😯😻😹', '🙒🚙😬', '😿🚴😴', '🚂😦🙨', '🛝😉🙒', '😵🚃🚜', '🛆😘😊', '🚟😌😿', '🙧😉🚍', '🛓🚥😢', '🚵😊😩', '😬😠🛡', '🚜😰🚏', '🚗🙸🚌', '😓🚲😆', '🛌😺🙍', '😳🚦🙍', '🚏😏🙏', '😆😰🚯', '🙊😳😻', '😤🙍🙀', '😻🛔🚷', '🛈🛋\U0001f6db', '🚊🙸🛀', '🚒🙟😓', '😧🚰🙬', '🚳🛏😓', '🛍😨🛆', '🙬😗🙐', '🙈😱🙒', '🚄🚆🛖', '\U0001f6d8🙔🙏', '🚱🙊🛖', '🚮🛀🛀', '🙁🙽🛖', '🚵🚾🚣', '🚣🙇🚰', '😎🙏🚃', '🚿🚎🚯', '🙄🛎😁', '🙚😻🙅', '🚕🚯😓', '🙊😎😸', '😘🙍🙬', '😧🚰🙫', '🙷🙀😮', '🙳🙩🙟', '🚁🙦🛆', '🚴😊🙏', '😼😆🛄', '🛡🙳🙒', '😋😖🙕', '🙽😞🙩', '🚊🙐\U0001f6db', '🙙🚡🚄', '😿🙲🛇', '🚜🙤😶', '🛉🙨😒', '😯😚🚣', '🙾🚍🙅', '🚾🚀😓', '🚅\U0001f6db🙟', '😿😲🙏', '🚓🛌🙅', '🚍🚓😹', '😬🙶🛍', '🚦🛒\U0001f6db', '🚑😚🙩', '🚂🙎😊', '😧😚🛂', '🙫🚭🛍', '😚🙷😿', '😍🙈🚷', '🚀😊🛖', '😉😖😁', '😆🙑😋', '🛍😤🚾', '🙙😶🙩', '🛔🚄🛏', '🚚🛌🙩', '😚🛉🚿', '😳🙕😩', '🚍🚛😪', '🙄🙱🛓', '🙑🙨😕', '🛄🙗🚇', '😺🚿🙅', '😼🚰🛆', '😸🚧🛅', '🚑😶🚣', '🚽🛎\U0001f6db', '🙾🚏😕', '🛄🚩🚁', '😠😦😅', '🛈🙏🛓', '🚣🙜🛡', '🙹😦🛓', '🚶🚦😴', '🛌🚗😆', '😚😤😴', '😏🙬😋', '🙘🚇🚷', '🙒😷🛟', '😰😉🙕', '😾🛌😥', '🙳\U0001f6d8🚰', '😔\U0001f

In [12]:
emoticon_train_df['input_emoticon'] = strings_after_removal
emoticon_test_df['input_emoticon'] = remove_common_characters(emoticon_test_df['input_emoticon'].values, common_chars)

In [19]:
train_df = get_char_columns(emoticon_train_df)
test_df = get_char_columns(emoticon_test_df)
x_train, x_valid, y_train, y_valid = one_hot_encode(train_df, test_df)
# print(x_train.shape, x_valid.shape, y_train.shape, y_valid.shape)

(7080, 501) (489, 501)
(7080, 501) (489, 501) (7080,) (489,)


In [ ]:
from models import predict_mlp


In [15]:
# oh_X_train, oh_X_val, y_train, y_val = one_hot_encode(emoticon_train_df, emoticon_test_df)

# oh_y_pred = predict_logistic_regression(oh_X_train, y_train, oh_X_val)

In [20]:
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report

# Train the MLP model (assuming you have already trained it)
mlp_model = MLPClassifier(hidden_layer_sizes=(16,), max_iter=1000)
mlp_model.fit(x_train, y_train)

# Predict probabilities for each class (softmax output for all samples)
y_proba_mlp = mlp_model.predict_proba(x_valid)

# Display softmax probabilities for all samples
print("Softmax probabilities for all samples:\n", y_proba_mlp)

Softmax probabilities for all samples:
 [[9.56090405e-04 9.99043910e-01]
 [2.13558318e-08 9.99999979e-01]
 [1.00000000e+00 2.04260712e-27]
 [9.99999997e-01 2.90756128e-09]
 [4.55286105e-06 9.99995447e-01]
 [2.53751464e-10 1.00000000e+00]
 [1.01035301e-08 9.99999990e-01]
 [9.99999999e-01 1.13935484e-09]
 [9.99999997e-01 2.75185118e-09]
 [6.54488819e-09 9.99999993e-01]
 [1.00000000e+00 3.43064038e-17]
 [1.15298500e-06 9.99998847e-01]
 [9.82407809e-01 1.75921908e-02]
 [1.30887186e-07 9.99999869e-01]
 [2.07771105e-01 7.92228895e-01]
 [1.00000000e+00 1.88464854e-17]
 [2.44340861e-06 9.99997557e-01]
 [3.30598429e-08 9.99999967e-01]
 [6.53761090e-09 9.99999993e-01]
 [1.00000000e+00 4.77980850e-22]
 [9.99999996e-01 3.95652556e-09]
 [3.52970075e-09 9.99999996e-01]
 [1.00000000e+00 2.32213370e-19]
 [1.00000000e+00 4.02264460e-34]
 [9.88309467e-01 1.16905334e-02]
 [1.00000000e+00 1.24799399e-19]
 [1.54078185e-03 9.98459218e-01]
 [2.06117807e-06 9.99997939e-01]
 [9.99999911e-01 8.91409257e-08]
 [2

### Feature

In [38]:
train_X = feature_train_df['features']
train_X = train_X.reshape(train_X.shape[0], -1)
train_Y = feature_train_df['label']
valid_X = feature_test_df['features']
valid_X = valid_X.reshape(valid_X.shape[0], -1)
valid_Y = feature_test_df['label']

In [39]:
import sklearn.linear_model


def predict_proba_logistic_regression(x_train, y_train, x_val, max_iter=1000, random_state=42) :
    '''
    inputs : training data and validation data in dataframe
    outputs : validation predictions and truth values
    '''
    
    lr_model = sklearn.linear_model.LogisticRegression(max_iter=max_iter, random_state=random_state)
    lr_model.fit(x_train, y_train)
    
    y_pred = lr_model.predict_proba(x_val)

    return y_pred


In [40]:
print(train_X.shape, train_Y.shape, valid_X.shape, valid_Y.shape)

(7080, 9984) (7080,) (489, 9984) (489,)


In [41]:
feat_y_pred = predict_proba_logistic_regression(train_X, train_Y, valid_X)

In [43]:
feat_y_pred

array([[1.91024476e-01, 8.08975524e-01],
       [7.85918078e-06, 9.99992141e-01],
       [9.99999991e-01, 9.33003465e-09],
       [9.97537566e-01, 2.46243389e-03],
       [3.42360182e-02, 9.65763982e-01],
       [1.28138306e-08, 9.99999987e-01],
       [3.06185482e-05, 9.99969381e-01],
       [9.97943854e-01, 2.05614629e-03],
       [9.91753987e-01, 8.24601327e-03],
       [1.46937267e-05, 9.99985306e-01],
       [9.99986377e-01, 1.36233542e-05],
       [1.70916593e-02, 9.82908341e-01],
       [7.19427775e-01, 2.80572225e-01],
       [1.60021715e-03, 9.98399783e-01],
       [6.63719184e-01, 3.36280816e-01],
       [9.99988798e-01, 1.12022578e-05],
       [8.22496733e-03, 9.91775033e-01],
       [6.94133423e-05, 9.99930587e-01],
       [3.02687930e-06, 9.99996973e-01],
       [9.99999889e-01, 1.10927972e-07],
       [9.95637204e-01, 4.36279605e-03],
       [9.96645047e-06, 9.99990034e-01],
       [9.99999451e-01, 5.49381969e-07],
       [1.00000000e+00, 7.41372573e-11],
       [7.277762

### Text

In [23]:
import os
import sys

import pandas as pd
import numpy as np
import typing

sys.path.append(os.path.abspath("../common"))  # add path to common functions
from evaluate import evaluate_predictions
from preprocess import getdfs, get_char_columns
from preprocess import one_hot_encode
from models import predict_logistic_regression
from models import predict_xgboost

emo_df, emo_val_df = getdfs('emoticon')

In [24]:
emo_df = get_char_columns(emo_df)
emo_df.head()


c_1 c_2 c_3 c_4 c_5 c_6 c_7 c_8 c_9 c_10 c_11 c_12 c_13  label
0   😛   🛐   😻   😑   😣   🙠   🙯   🚼   😒    🙼    😑    🙯    😣      0
1   🛐   😑   😪   😛   🚼   🙯   😣   🚅   😑    🙯    😹    😣    🙼      0
2   😛   🙯   😑   🚡   😣   🚼   🛐   🙲   😣    🙯    🛑    😑    🙼      0
3   😛   🚼   🛐   🙐   😣   🙯   😑   🙪   😑    🙼    🛆    😣    🙯      1
4   🛐   🚟   🚼   😛   🙋   😑   😣   🙯   😹    🙯    😑    😣    🙼      1

In [25]:

repeat_emos = ['🙼', '🛐', '🙯', '😛', '😣', '😑', '🚼']

repeat_emo_code = {
     '🙼' : '284',
     '🛐' : '464', 
     '🙯' : '262',
     '😛' : '15436', 
     '😣' : '614',
     '😑' : '1596', 
     '🚼' : '422'
}

In [54]:
# model.eval()  # Set the model to evaluation mode
# correct = 0
# total = 0

# text_pred = []

# with torch.no_grad():
#     for sequences, labels in valid_loader:
#         sequences = sequences.unsqueeze(1).to(device)
#         labels = labels.unsqueeze(1).to(device)
        
#         outputs = model(sequences)
#         predicted = (outputs > 0.5).float()
#         text_pred.extend(predicted.cpu().numpy())
#         total += labels.size(0)
#         correct += (predicted == labels).sum().item()

# accuracy = correct / total
# text_pred = np.array(text_pred).flatten()
# print(f'Validation Accuracy: {accuracy * 100:.2f}%')

Validation Accuracy: 72.39%


In [26]:
def remove_substrings(input_string, substrings):
    """
    Removes all occurrences of substrings from the input string.

    Parameters:
    input_string (str): The string to remove substrings from.
    substrings (list): List of substrings to remove from the input string.

    Returns:
    str: The input string with substrings removed.
    """
    for substring in substrings:
        input_string = input_string.replace(substring, "")
    return input_string

def process_strings ( strs : typing.List[str] )-> typing.List[str]:
    strs = [x.lstrip('0') for x in strs]

    # Example usage
    substrings = repeat_emo_code.values()

    # Remove the substrings
    strs = [remove_substrings(input_string, substrings) for input_string in strs]

    padded_strs = []

    for s in strs:
        if len(s) < 15:
            s = s + '0'*(15-len(s))
        padded_strs.append(s)

    return padded_strs

text_seq_train_df['input_str'] = process_strings(text_seq_train_df['input_str'])
text_seq_test_df['input_str'] = process_strings(text_seq_test_df['input_str'])

In [28]:
num_feat = 15

def get_columns (df) :
    for i in range(num_feat):
        df[f'c_{i}'] = df['input_str'].apply(lambda x : x[i])
    return df.drop(columns = ['input_str'])

text_seq_train_df = get_columns(text_seq_train_df)
text_seq_test_df = get_columns(text_seq_test_df)

In [29]:
text_seq_test_df.head()

label c_0 c_1 c_2 c_3 c_4 c_5 c_6 c_7 c_8 c_9 c_10 c_11 c_12 c_13 c_14
0      1   3   3   4   1   4   1   3   9   0   1    0    0    0    0    0
1      1   1   2   5   0   6   2   3   2   7   3    1    0    4    0    0
2      0   4   5   4   3   6   3   3   6   5   2    7    1    3    0    0
3      0   1   1   2   0   4   3   7   1   3   1    3    2    0    0    0
4      1   3   3   2   4   2   3   6   8   4   5    7    0    5    0    0

In [30]:
# Feature engineering (example: one-hot encoding)
from sklearn.preprocessing import OneHotEncoder
from preprocess import one_hot_encode

train_df, valid_df, y_train, y_valid = one_hot_encode(text_seq_train_df, text_seq_test_df)

(7080, 142) (489, 142)


In [32]:
x_train = train_df.values
x_valid = valid_df.values

In [36]:
def predict_xgboost(x_train, y_train, x_valid, return_proba=False):
    from xgboost import XGBClassifier
    model = XGBClassifier()
    model.fit(x_train, y_train)
    
    if return_proba:
        return model.predict_proba(x_valid)
    else:
        return model.predict(x_valid)

# Then, you call the function with:
y_pred_xgb_proba = predict_xgboost(x_train, y_train, x_valid, return_proba=True)
print("XGBoost Softmax probabilities:\n", y_pred_xgb_proba)

XGBoost Softmax probabilities:
 [[3.30577672e-01 6.69422328e-01]
 [2.19777822e-02 9.78022218e-01]
 [9.17848706e-01 8.21512863e-02]
 [6.42301679e-01 3.57698321e-01]
 [2.16126382e-01 7.83873618e-01]
 [1.88156366e-02 9.81184363e-01]
 [1.09102130e-01 8.90897870e-01]
 [9.74427581e-01 2.55724415e-02]
 [6.72921717e-01 3.27078283e-01]
 [4.61164713e-02 9.53883529e-01]
 [9.48541224e-01 5.14587983e-02]
 [5.75559735e-01 4.24440235e-01]
 [3.56216252e-01 6.43783748e-01]
 [6.92198277e-02 9.30780172e-01]
 [3.56010020e-01 6.43989980e-01]
 [8.38934600e-01 1.61065415e-01]
 [3.71527970e-01 6.28472030e-01]
 [7.87407339e-01 2.12592646e-01]
 [7.25730658e-02 9.27426934e-01]
 [9.64978635e-01 3.50213423e-02]
 [6.32948875e-01 3.67051095e-01]
 [1.72687352e-01 8.27312648e-01]
 [9.66802001e-01 3.31980065e-02]
 [9.68041301e-01 3.19587030e-02]
 [6.46338463e-01 3.53661567e-01]
 [9.00904894e-01 9.90951210e-02]
 [4.97735262e-01 5.02264738e-01]
 [2.44548261e-01 7.55451739e-01]
 [6.13749385e-01 3.86250615e-01]
 [2.4045407

In [44]:
emoti = y_proba_mlp
feat = feat_y_pred
seq = y_pred_xgb_proba

In [45]:
emoti.shape, feat.shape, seq.shape

((489, 2), (489, 2), (489, 2))

In [72]:
hard_pred = np.array((np.argmax(emoti, axis = 1) + np.argmax(feat, axis = 1) + np.argmax(seq, axis = 1)) >= 2, dtype = np.float64)
rep = get_classification_report(hard_pred, y_valid)
print(rep)

              precision    recall  f1-score   support

     Class 0       0.97      0.97      0.97       253
     Class 1       0.97      0.97      0.97       236

    accuracy                           0.97       489
   macro avg       0.97      0.97      0.97       489
weighted avg       0.97      0.97      0.97       489



In [64]:
soft_pred = np.argmax(emoti + feat + seq, axis = 1)
rep = get_classification_report(soft_pred, y_valid.values)
print(rep)

              precision    recall  f1-score   support

     Class 0       0.96      0.97      0.97       251
     Class 1       0.97      0.96      0.96       238

    accuracy                           0.97       489
   macro avg       0.97      0.97      0.97       489
weighted avg       0.97      0.97      0.97       489



In [61]:
y_valid.values

array([1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,